export {default as Pages } from './Pages/Index'
export {default as ShowPage} from './Pages/Show'
export {default as NewPage} from './Pages/New'
export {default as EditPage} from './Pages/Edit'
export {default as Login} from './Login'
export {default as Reserve} from './Reserve/Index'
export {default as ReserveList} from './Reserve/ReserveList'
export {default as RoomsCol} from './Rooms/Index'
export {default as NewRooms} from './Rooms/NewRooms'
export {default as EditRoomscol} from './Rooms/EditFormCol'
export {default as Home} from './Home'
export {default as CheckAuthed} from './CheckAuthed'
export {default as Users} from './Users/Index'
export {default as ShowUser} from './Users/Show'
export {default as NewUser} from './Users/New'
export {default as EditUser} from './Users/Edit'
export {default as ResetPass} from './Users/ResetPass'